meta-printnanny/recipes-core/images/printnanny-base.bb, meta-printnanny/recipes-core/images/printnanny-rpi.bb, meta-printnanny/wic/sdimage-printnanny-rpi.wks, meta-printnanny/wic/sdimage-printnanny.wks
This image class doesn't update /etc/fstab with boot partition.
https://github.com/agherzan/meta-raspberrypi/blob/master/classes/sdcard_image-rpi.bbclass
Instead, use OpenEmbedded Kickstart commands to create partition table + update fstab with `flush` (boot) and `noatime` (rootfs) options. https://docs.yoctoproject.org/ref-manual/kickstart.html
=> Replace rpi-sdimg IMAGE_FSTYPE with wks

conf/distro/bitsy.conf, meta-printnanny/conf/distro/printnanny.conf, meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-core.bb, meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-sys.bb, meta-printnanny/recipes-extended/cloud-init/cloud-init/001-telemetry.cfg, meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud.cfg, meta-printnanny/recipes-extended/cloud-init/cloud-init_%.bbappend, meta-printnanny/recipes-multimedia/packagegroups/packagegroup-printnanny-multimedia.bb, recipes-extended/cloud-init/cloud-init_22.2.bb
* Pass --distro to `setup.py install` - otherwise python3native install will detect host system distro for packaging/templating purposes
* Use /var/lib/cloud/seed/ to seed NoCloud datasource
* Needed to override setuptools3_legacy_do_install() to just call `setup.py install` - the default implementation invokes `setup.py build --skip-build install` for reasons I don't quite understand atm, but ¯\_(ツ)_/¯
=> Fix cloudinit install quirks

conf/distro/bitsy.conf, meta-printnanny/recipes-core/images/printnanny-core-image.bb, recipes-bsp/bootfiles/rpi-cmdline.bbappend
🎉 
```
root@raspberrypi4-64:~# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/root                764M  394M  314M  56% /
devtmpfs                 3.8G     0  3.8G   0% /dev
/data/overlay-etc/upper  764M  394M  314M  56% /etc
tmpfs                    3.9G     0  3.9G   0% /dev/shm
tmpfs                    1.6G  9.0M  1.6G   1% /run
tmpfs                    4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs                    3.9G     0  3.9G   0% /tmp
tmpfs                    3.9G  168K  3.9G   1% /var/volatile
/dev/mmcblk0p1            71M   46M   26M  65% /boot
```
=> Fix overlayfs-etc initialization

meta-printnanny/recipes-core/printnanny-apps/files/Rocket.toml, meta-printnanny/recipes-core/printnanny-apps/files/printnanny-dash.service, meta-printnanny/recipes-core/printnanny-apps/files/printnanny-generator.sh, meta-printnanny/recipes-core/printnanny-apps/files/printnanny-mqtt.service, meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb, meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud.cfg, meta-printnanny/recipes-httpd/nginx/nginx/dash.locations.template, meta-printnanny/recipes-httpd/nginx/nginx/nginx.service, meta-printnanny/recipes-httpd/nginx/nginx/octoprint.locations.template, meta-printnanny/recipes-httpd/nginx/nginx/server.conf.template, meta-printnanny/recipes-httpd/nginx/nginx_%.bbappend, recipes-core/bitsy-tweaks/files/getty@tty1.service.d/50-noclear.conf, recipes-extended/cloud-init/cloud-init_22.2.bb, recipes-multimedia/janus-gateway/janus-gateway_0.11.8.bb
2fa flow is currently failing with the following error, will tackle that in the next PR.
```
Jun 07 15:47:22 pn-05-24 printnanny-dash[654]: Reading public key from "/etc/printnanny/keys/ec_public.pem"
Jun 07 15:47:22 pn-05-24 printnanny-dash[654]: Error: Error de/serializing content IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jun 07 15:47:22 pn-05-24 printnanny-dash[654]:    >> Outcome: Success
Jun 07 15:47:22 pn-05-24 printnanny-dash[654]:    >> Response succeeded.
```
=> Service ordering of cloud-init, printnanny-generator, nginx is working

recipes-bsp/bootfiles/files/vendor-data.yaml
Should fix the following warning during first boot:
```
[   31.099531] cloud-init[450]: 2022-05-24 21:33:01,334 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'b'---'...'
```
=> Remove separator to resolve unhandled multipart error from cloud-init

recipes-multimedia/janus-gateway/files/janus-gateway.service
Fixes transient error during fast startup:
```
Jun 23 15:35:30 pn-octo janus-gateway[423]: STUN server to use: stun.l.google.com:19302
Jun 23 15:35:30 pn-octo janus-gateway[423]: [ERR] [../../janus-gateway-1.0.2/src/ice.c:janus_ice_set_stun_server:1153] Could not resolve stun.l.google.com...
Jun 23 15:35:30 pn-octo janus-gateway[423]: [FATAL] [../../janus-gateway-1.0.2/src/janus.c:main:4997] Invalid STUN address stun.l.google.com:19302
Jun 23 15:35:30 pn-octo systemd[1]: janus-gateway.service: Main process exited, code=exited, status=1/FAILURE
Jun 23 15:35:39 pn-octo janus-gateway[560]: Reading credentials from /run/credentials/janus-gateway.service
Jun 23 15:35:39 pn-octo janus-gateway[561]: cat: /run/credentials/janus-gateway.service/janus-edge-admin-secret: No such file or directory …
```
=> double sleep time before attempting to add janus token

meta-printnanny/recipes-core/octoprint-apps/files/config.yaml, meta-printnanny/recipes-core/octoprint-apps/files/octoprint-venv.service.tmpl, meta-printnanny/recipes-core/printnanny-apps/files/printnanny-cam.service, meta-printnanny/recipes-core/printnanny-apps/files/printnanny-dash.service, meta-printnanny/recipes-core/printnanny-apps/files/printnanny-link-confd.sh, meta-printnanny/recipes-core/printnanny-apps/files/printnanny-rtp-server.service, meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb, meta-printnanny/recipes-core/printnanny-rs/printnanny-gst_0.23.0.bb, recipes-bsp/bootfiles/rpi-cmdline.bbappend, recipes-bsp/bootfiles/rpi-config_%.bbappend, recipes-multimedia/janus-gateway/files/janus.plugin.streaming.jcfg
After some experimentation, I suspect running tflite and video encoding in one pipeline is the cause of stutters/freezing due to synchronization issues (example pipeline below). One tee stream is intended to run in near-realtime, while the other tee stream is much slower and should drop frames via leaky buffer.
```
gst-launch-1.0 --verbose libcamerasrc \
! capsfilter caps="video/x-raw,format=RGB,width=640,height=480,framerate=0/1" \
! tee name=t \
t.  ! queue leaky=2 max-size-buffers=2 \
! videoconvert \
! videoscale ! video/x-raw,width=320,height=320 \
! tensor_converter \
! tensor_transform mode=arithmetic option=typecast:uint8,add:0,div:1 \
! other/tensors,num_tensors=1,format=static \
! tensor_filter \
framework=tensorflow2-lite \
model=/usr/share/printnanny/model/model.tflite \
! …
```
=> Implement printnanny-rtp-server.service

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-online.target, meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb, meta-printnanny/recipes-extended/cloud-init/cloud-init/003-runcmd.cfg
This snippet is being rendered as one string:
```
root@raspberrypi4-64:~# cat /var/lib/cloud/instance/scripts/runcmd
#!/bin/sh
'systemctl restart avahi-daemon.service'
```
This results in the `cloud-final.service` failing with error:
```
May 24 21:34:55 raspberrypi4-64 cloud-init[703]: Cloud-init v. 22.2 running 'modules:final' at Tue, 24 May 2022 21:34:55 +0000. Up 143.26 seconds.
May 24 21:34:55 raspberrypi4-64 cloud-init[703]: /var/lib/cloud/instance/scripts/runcmd: line 2: systemctl restart avahi-daemon.service: command not found
````
=> Fix formatting of runcmd

recipes-extended/cloud-init/cloud-init_22.2.bb
I suspect the dependency on `sshd.socket` here is causing the following conflict:
```
root@pn-0-3-0:~# systemctl start sshd.service
Failed to start sshd.service: Transaction contains conflicting jobs 'stop' and 'start' for sshd.service. Probably contradicting requirement dependencies configured.
See system logs and 'systemctl status sshd.service' for details.
```
=> Fix transaction race for sshd.service

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-cloud-sync.service
TLS verification fails if performed before NTP syncs system clock
```
y 24 14:33:19 demo-0-3-0 printnanny-cloud-sync[635]: Error: error in reqwest: error sending request for url (https://api.printnanny.ai/api/pis/45/system-info/update-or-create/): error trying to connect: error:0A000086:SSL routines:tls_post_process_>
May 24 14:33:19 demo-0-3-0 printnanny-cloud-sync[635]: Caused by:
May 24 14:33:19 demo-0-3-0 printnanny-cloud-sync[635]:     0: error sending request for url (https://api.printnanny.ai/api/pis/45/system-info/update-or-create/): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate>
May 24 14:33:19 demo-0-3-0 printnanny-cloud-sync[635]:     1: error trying to connect: error:0A000086:SSL …
```
=> start printnanny-cloud-sync after systemd-timesyncd.service

meta-printnanny/recipes-3dprinter/mainsail/mainsail.bb, meta-printnanny/recipes-httpd/nginx/nginx/mainsail.locations.template
closes: https://github.com/bitsy-ai/printnanny-os/issues/146
=> Bump mainsail to support-base-path-rc2

meta-printnanny/recipes-3dprinter/klipper/klipper_git.bb
Klipper has a runtime dependency on gcc. Klippy server is currently failing to start with error:
```
Nov 14 15:33:11 pn-v0-4 systemd[1]: Started Starts Klipper and provides klippy Unix Domain Socket API.
Nov 14 15:33:13 pn-v0-4 python3[836]: sh: line 1: gcc: command not found
```
=> Ship gcc compiler with klipper package

meta-printnanny/recipes-3dprinter/mainsail/files/mainsail.target, meta-printnanny/recipes-3dprinter/moonraker/files/moonraker.service, meta-printnanny/recipes-core/octoprint-apps/files/octoprint.service, meta-printnanny/recipes-core/printnanny-cloud-apps/files/printnanny-cloud.target
Observed while monitoring a boot via serial terminal:
```
[    5.317650] systemd[1]: /lib/systemd/system/printnanny-cloud.target:4: Unknown section 'Service'. Ignoring.
[    5.354162] systemd[1]: /lib/systemd/system/octoprint.service:20: Unbalanced quoting, ignoring: "/bin/bash -c "${OCTOPRINT_VENV}/bin/python -m octoprint serve      --host 127.0.0.1      --config "${OCTOPRINT_CONFIG}"      --port "${OCTOPRINT_PORT}""
[    5.376673] systemd[1]: octoprint.service: Unit configuration has fatal error, unit will not be started.
[    5.412569] systemd[1]: /lib/systemd/system/mainsail.target:4: Unknown section 'Service'. Ignoring.
[    5.425614] systemd[1]: /lib/systemd/system/moonraker.service:24: Unbalanced quoting, ignoring: "/var/lib/moonraker/.venv/bin/python3 …
```
=> fix a handful of systemd config issues

meta-printnanny/recipes-core/octoprint-apps/files/octoprint.service
This produced an invalid systemd unit that caused postinst failure during image build:
```
WARNING: printnanny-release-image-1.0-r0 do_rootfs: octoprint-apps.postinst returned 1, marking as unpacked only, configuration required on target.
ERROR: printnanny-release-image-1.0-r0 do_rootfs: Postinstall scriptlets of ['octoprint-apps'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
Details of the failure are in /poky/build/tmp/work/raspberrypi4_64-bitsy-linux/printnanny-release-image/1.0-r0/temp/log.do_rootfs.
ERROR: Logfile of failure stored in: /poky/build/tmp/work/raspberrypi4_64-bitsy-linux/printnanny-release-image/1.0-r0/temp/log.do_rootfs.323
ERROR: …
```
=> fix github suggestion artifact(?)

conf/distro/bitsy.conf, meta-printnanny/conf/distro/printnanny.conf, meta-printnanny/conf/layer.conf, meta-printnanny/recipes-core/printnanny-gst-plugin/printnanny-gst-plugin.inc, meta-printnanny/recipes-core/printnanny-gst-plugin/printnanny-gst-plugin_0.4.0.bb, meta-printnanny/recipes-nnstreamer/nnstreamer/nnstreamer_%.bbappend
Fixes missing `/usr/lib/nnstreamer/filters/libnnstreamer_filter_tensorflow2-lite.so` shared obj, which is causing `printnanny-vision.service` to fail with error `Cannot identify the given neural network framework, tensorflow2-lite`
```
pn-v0-4:~$ ls /usr/lib/nnstreamer/filters/
libnnstreamer_filter_cpp.so
```
```
Dec 01 14:36:59 pn-v0-4 printnanny-vision[1197]: [2022-12-01T22:36:59Z WARN  printnanny_gst_pipeline] octoprint compatibility enabled, writing hls segments/playlist to /var/run/printnanny-hls/segment%05d.ts /var/run/printnanny-hls/playlist.m3u8
Dec 01 14:36:59 pn-v0-4 printnanny-gst-[1197]: Cannot identify the given neural network framework, tensorflow2-lite
Dec 01 14:36:59 pn-v0-4 printnanny-vision[1197]: 0:00:03.773412720  1197   0x558ac0d670 WARN           basetransform …
```
=> Fix printnanny-gst-plugin package RDEPENDS

meta-printnanny/recipes-extended/nats-server/nats-server_2.9.9.bb
closes: https://github.com/bitsy-ai/printnanny-os/issues/133
=> upgrade nats-server recipe to 2.9.9

recipes-multimedia/libcamera/libcamera_0.0.2.bb
ref: https://github.com/bitsy-ai/printnanny-os/issues/158
=> Fix: libcamera missing USB camera pipeline/ipa module

meta-printnanny/recipes-3dprinter/moonraker/files/moonraker-venv.service, meta-printnanny/recipes-core/printnanny-core-apps/files/printnanny-edge-nats.service
Fixes the following error in Moonraker startup:
```
May 24 14:32:52 raspberrypi4-64 bash[457]: #################################################################
May 24 14:32:52 raspberrypi4-64 bash[457]: All Configuration Files:
May 24 14:32:52 raspberrypi4-64 bash[457]: /home/printnanny/.config/printnanny/vcs/moonraker/moonraker.conf
May 24 14:32:52 raspberrypi4-64 bash[457]: #################################################################
May 24 14:32:52 raspberrypi4-64 bash[457]: [moonraker.py:add_warning()] - Unable to create data path folder at /home/printnanny/.local/share/moonraker
May 24 14:32:52 raspberrypi4-64 bash[457]: [app.py:register_local_handler()] - Registering HTTP Endpoint: (GET) /server/info
```
=> Create moonraker data dir in moonraker-venv service

recipes-bsp/bootfiles/rpi-cmdline.bbappend
ref: https://github.com/bitsy-ai/printnanny-os/issues/189
=> allocate a CMA heap of 256M

meta-printnanny/recipes-core/printnanny-cloud-apps/files/printnanny-cloud-sync.service
closes: https://github.com/bitsy-ai/printnanny-os/issues/222
=> fix: printnanny-cloud-sync.service start command

recipes-extended/cloud-init/cloud-init_22.4.2.bb
ref: https://github.com/bitsy-ai/printnanny-os/issues/234
=> Provide blkid as runtime dependency for cloud-init 22.4

meta-printnanny/recipes-core/octoprint-apps/files/octoprint.service, meta-printnanny/recipes-core/printnanny-cloud-apps/files/printnanny-cloud-nats.service, meta-printnanny/recipes-core/printnanny-core-apps/files/printnanny-edge-nats.service, meta-printnanny/recipes-core/printnanny-vision/files/printnanny-vision.service, meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud-config.service, meta-printnanny/recipes-multimedia/janus-gateway/files/janus-gateway.service, recipes-multimedia/janus-gateway/files/janus-gateway.service
Services with a `Wants=network-online.target` dependency are getting restarted when the network is unavailable. 
ref: https://github.com/bitsy-ai/printnanny-os/issues/282
=> Fix: remove Wants=network-online.target dependency, keep After=network-online.target ordering

meta-printnanny/recipes-3dprinter/mainsail/mainsail.bb
ref: https://github.com/bitsy-ai/printnanny-os/issues/263
=> Install mainsail from tag: 2.5.0-beta1-printnanny-support-base-path-2023-02-25

meta-printnanny/recipes-3dprinter/klipper/files/klipper.service, meta-printnanny/recipes-3dprinter/moonraker/files/moonraker.service, meta-printnanny/recipes-core/octoprint/files/octoprint.service, meta-printnanny/recipes-core/printnanny-cloud-apps/files/printnanny-cloud-sync.service, meta-printnanny/recipes-core/printnanny-core-apps/files/printnanny-edge-nats.service, meta-printnanny/recipes-core/printnanny-core-apps/files/printnanny-init.service, meta-printnanny/recipes-core/printnanny-core-apps/files/printnanny-motd.service, meta-printnanny/recipes-core/printnanny-core-apps/files/printnanny-settings.service, meta-printnanny/recipes-core/printnanny-dash/files/printnanny-dash.service, meta-printnanny/recipes-core/printnanny-rs/files/printnanny-snapshot.service, meta-printnanny/recipes-core/printnanny-vision/files/printnanny-vision.target, meta-printnanny/recipes-extended/nats-server/files/printnanny-nats-server.service
Fixes some ordering cycle issues:
```
May  8 00:58:51 rpi4b4g-imx708 systemd[1]:  multi-user.target: Found ordering cycle on octoprint.service/start
May  8 00:58:51 rpi4b4g-imx708 systemd[1]:  multi-user.target: Found dependency on cloud-init.target/start
May  8 00:58:51 rpi4b4g-imx708 systemd[1]:  multi-user.target: Found dependency on cloud-final.service/start
May  8 00:58:51 rpi4b4g-imx708 systemd[1]:  multi-user.target: Found dependency on multi-user.target/start
May  8 00:58:51 rpi4b4g-imx708 systemd[1]:  multi-user.target: Job octoprint.service/start deleted to break ordering cycle starting with multi-user.target/start
May  8 00:58:52 rpi4b4g-imx708 systemd[1]:  multi-user.target: Found ordering cycle on mainsail.target/start
May  8 00:58:52 rpi4b4g-imx708 systemd[1]: …
```
=> fix: cloud-init dep cycle
