meta-printnanny/recipes-extended/cloud-init/cloud-init_%.bbappend
recipes-extended/cloud-init/cloud-init_22.2.bb

https://github.com/bitsy-ai/cloud-init/commit/bdd31f064034f6aa8c5d4f96f385b2d0ceaffb08

Pull in /etc/host revisions for cloud-init

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-generator.sh
meta-printnanny/recipes-core/python3-octoprint-nanny/files/octoprint.service
meta-printnanny/recipes-core/python3-octoprint-nanny/python3-octoprint-nanny_0.11.0.bb
recipes-multimedia/gstreamer-apps/gstreamer-apps.bb
recipes-multimedia/janus-gateway/files/janus.jcfg.template
recipes-multimedia/janus-gateway/janus-gateway_1.0.2.bb
recipes-multimedia/recipes-support/libsrtp/libsrtp_%.bbappend
recipes-support/libsrtp/libsrtp_%.bbappend

* Upgrade OctoPrint-Nanny to 0.11.0
* Compile libsrtp with openssl support to handle DTLS w/ AES GEM
* Link janus API token to octoprint.service.d
* Enable gstreamer service by default

More Janus & WebRTC debugging

---

meta-printnanny/recipes-core/images/printnanny-core-image.bb
meta-printnanny/recipes-multimedia/packagegroups/packagegroup-printnanny-cv.bb
meta-printnanny/recipes-nnstreamer/nnstreamer-models/files/nnstreamer-rtph264pay.sh
meta-printnanny/recipes-nnstreamer/nnstreamer-models/files/nnstreamer.service
meta-printnanny/recipes-nnstreamer/nnstreamer-models/nnstreamer-models.bb
meta-printnanny/recipes-support/packagegroups/packagegroup-printnanny-utils.bb

install htop via printnanny-utils packagegroup

---

meta-printnanny/recipes-extended/cloud-init/cloud-init/001-fix-perms.sh
meta-printnanny/recipes-extended/cloud-init/cloud-init_%.bbappend
recipes-core/packagegroups/packagegroup-bitsy.bb

https://github.com/bitsy-ai/printnanny-os/issues/14
🎉 
```
root@pn-octo:~# sudo -u printnanny vcgencmd get_throttled
throttled=0x0
```

Fix /dev vcos permissions in per-boot script

---

meta-printnanny/recipes-core/systemd/systemd/050-wait-for-network-override.conf
meta-printnanny/recipes-core/systemd/systemd_%.bbappend

https://github.com/bitsy-ai/printnanny-os/issues/21

systemd-networkd-wait-online.service succeeds when at least one interface is alive

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-mqtt.service

… mode is different. (File system: 775 ConfigurationDirectoryMode: 755)

fix warning: ConfigurationDirectory printnanny already exists

---

meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-core.bb
meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb
meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud-config.service
meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud-init-local.service
meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud-init.service

https://github.com/bitsy-ai/printnanny-os/issues/23

Write cloud-init service start/stop points to psplash-write MSG buffer

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-license.service

https://github.com/bitsy-ai/printnanny-os/issues/23

Add check license psplash msg

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-online.service
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-online.target
meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb

https://github.com/bitsy-ai/printnanny-os/issues/23

implement printnanny-online.service

---

meta-printnanny/recipes-core/python3-octoprint/files/0001-shim-startPrintNannyWebRTC-if-available.patch
meta-printnanny/recipes-core/python3-octoprint/python3-octoprint-nanny_git.bb
meta-printnanny/recipes-core/python3-octoprint/python3-octoprint_1.8.1.bb

See: https://github.com/bitsy-ai/printnanny-os/issues/26

Prefer startPrintNannyWebRTC to OctoPrint's own startWebRTC if available

---

meta-printnanny/recipes-core/common/printnanny-user.bb
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-link-confd.sh
recipes-core/udev/files/10-local-rpi.rules
recipes-core/udev/files/99-com.rules
recipes-core/udev/udev-rules-rpi.bbappend

x-ref: https://raw.githubusercontent.com/RPi-Distro/raspberrypi-sys-mods/master/etc.armhf/udev/rules.d/99-com.rules
closes: https://github.com/bitsy-ai/printnanny-os/issues/28

Raspberry Pi udev rules

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-motd.service
meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb
meta-printnanny/recipes-core/printnanny-rs/printnanny-cli_0.24.0.bb

closes https://github.com/bitsy-ai/printnanny-os/issues/30

Generate MoTD from issue txt

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-nats.service
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-online.target
meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/62

Replace printnanny-mqtt.service with printnanny-nats.service

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-cloud-sync.service
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-init.service
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-link-confd.sh
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-nats.service
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-sync.service
meta-printnanny/recipes-core/printnanny-apps/printnanny-apps.bb
meta-printnanny/recipes-core/printnanny-rs/printnanny-cli_git.bb
meta-printnanny/recipes-core/printnanny-swupdate/printnanny-swupdate-runner_0.2.0.bb
meta-printnanny/recipes-core/python3-octoprint/python3-octoprint-nanny_git.bb

* Split into printnanny-init so boot event can fire ASAP

Fix printnanny-sync service

---

meta-printnanny/recipes-core/printnanny-apps/files/printnanny-gst-cam.sh
meta-printnanny/recipes-core/printnanny-apps/files/printnanny-gst-vision.sh

related to https://github.com/bitsy-ai/printnanny-os/issues/84

Run printnanny config sync before initializing cam/vision gst services

---

recipes-extended/syncthing/files/syncthing@.service
recipes-extended/syncthing/syncthing_1.20.4.bb

https://github.com/bitsy-ai/printnanny-os/issues/77

implement syncthing recipe w/ systemd pkgconfig

---

conf/distro/bitsy.conf
meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-core.bb
recipes-extended/syncthing/files/syncthing.locations.conf
recipes-extended/syncthing/syncthing_1.20.4.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/77

add nginx location for syncthing

---

meta-printnanny/recipes-core/printnanny-rs/printnanny-cli_git.bb
meta-printnanny/recipes-core/python3-octoprint/python3-octoprint-nanny_0.13.4.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/82

Include disk usage and system uptime in SystemInfo

---

meta-printnanny/recipes-core/python3-octoprint/python3-octoprint_1.8.4.bb

closes https://github.com/bitsy-ai/printnanny-os/issues/96

upgrade OctoPrint to 1.8.4

---

meta-printnanny/recipes-core/python3-octoprint/python3-cchardet_2.1.7.bb
meta-printnanny/recipes-core/python3-octoprint/python3-octoprint_1.8.4.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/97

build cchardet package + pin as OctoPrint dependency

---

meta-printnanny/recipes-core/printnanny-gst-plugin/printnanny-gst-plugin_0.2.3.bb
meta-printnanny/recipes-core/printnanny-rs/printnanny-cli_git.bb
meta-printnanny/recipes-core/printnanny-vision/files/printnanny-vision.service
meta-printnanny/recipes-core/python3-octoprint/python3-octoprint-nanny_0.13.5.bb
recipes-multimedia/janus-gateway/files/janus.plugin.streaming.jcfg

ref https://github.com/bitsy-ai/printnanny-os/issues/103

Support hls+http gstreamer pipeline branch for OctoPrint video compatibility 

---

meta-printnanny/recipes-httpd/nginx/nginx/server.conf.template
meta-printnanny/recipes-httpd/nginx/nginx_%.bbappend

Co-authored-by: Tricia Bogen <tricia@cernu.us>

remove nginx welcome page

---

meta-printnanny/recipes-3dprinter/moonraker/files/moonraker.conf
meta-printnanny/recipes-3dprinter/moonraker/files/moonraker.service
meta-printnanny/recipes-3dprinter/moonraker/moonraker_git.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/104

Fix default moonraker.conf path

---

meta-printnanny/recipes-extended/cloud-init/cloud-init/003-runcmd.cfg
meta-printnanny/recipes-extended/cloud-init/cloud-init/avahi-daemon-after-cloud-init.conf
meta-printnanny/recipes-extended/cloud-init/cloud-init_%.bbappend
recipes-multimedia/janus-gateway/files/janus-gateway.service
recipes-multimedia/janus-gateway/files/janus.jcfg.template

https://github.com/bitsy-ai/printnanny-os/issues/137

Fix: Janus WebRTC Gateway sometimes fails to resolve mDNS address

---

meta-printnanny/recipes-3dprinter/klipper/files/klipper.service

closes: https://github.com/bitsy-ai/printnanny-os/issues/141

fix invalid cross device error

---

meta-printnanny/recipes-support/packagegroups/packagegroup-printnanny-utils.bb

closes: https://github.com/bitsy-ai/printnanny-os/issues/156

add tree to printnanny-utils packagegroup

---

meta-printnanny/recipes-core/images/include/core.inc
meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-tailscale.bb
recipes-connectivity/tailscale/tailscale_1.32.3.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/155

Install tailscale CLI + daemon

---

meta-printnanny/recipes-core/printnanny-dash/printnanny-dash_git.bb

release: https://github.com/bitsy-ai/printnanny-os/issues/157

[fix] include fix for footer min height

---

meta-printnanny/recipes-core/printnanny-rs/printnanny-cli_git.bb

release printnanny cli: https://github.com/bitsy-ai/printnanny-cli/pull/368
ref: https://github.com/bitsy-ai/printnanny-os/issues/158

List available camera devices

---

meta-printnanny/recipes-core/images/include/core.inc
meta-printnanny/recipes-core/images/include/klipper.inc
meta-printnanny/recipes-core/images/include/mainsail.inc
meta-printnanny/recipes-core/images/include/octoprint.inc

closes: https://github.com/bitsy-ai/printnanny-os/issues/160

Fix: IMAGE_INSTALL variable appends

---

meta-printnanny/recipes-httpd/nginx/nginx/dash.locations.template

closes: https://github.com/bitsy-ai/printnanny-os/issues/161

add a try_files directive

---

meta-printnanny/recipes-3dprinter/moonraker/moonraker_git.bb
recipes-connectivity/tailscale/files/tailscaled.service
recipes-connectivity/tailscale/tailscale_1.32.3.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/155

Fix tailscaled.service unit file

---

recipes-multimedia/janus-gateway/files/janus.plugin.streaming.jcfg

ref: https://github.com/bitsy-ai/printnanny-os/issues/173

disable videobufferkf

---

meta-printnanny/recipes-core/packagegroups/packagegroup-klipper.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/148

Install klipper-docs package

---

recipes-connectivity/tailscale/files/tailscaled.service
recipes-connectivity/tailscale/tailscale_1.32.3.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/155

add overlayfs for /var/lib/tailscale

---

meta-printnanny/recipes-core/images/files/raspberrypi4-64/sw-description
meta-printnanny/recipes-httpd/nginx/nginx/mainsail.locations.template
meta-printnanny/recipes-httpd/nginx/nginx/octoprint.locations.template
meta-printnanny/recipes-httpd/nginx/nginx/swupdate.locations.template

ref: https://github.com/bitsy-ai/printnanny-os/issues/186

Fix: swupdate patch should not buffer to disk

---

meta-printnanny/recipes-core/octoprint-apps/files/octoprint.service
meta-printnanny/recipes-httpd/nginx/nginx/octoprint.locations.template

ref: https://github.com/bitsy-ai/printnanny-os/issues/191

bind OctoPrint server to 0.0.0.0:5001

---

meta-printnanny/recipes-httpd/nginx/nginx/dash.locations.template

Rule out caching while debugging: https://github.com/bitsy-ai/printnanny-os/issues/192

Disable browser caching

---

meta-printnanny/recipes-httpd/nginx/nginx/dash.locations.template

Reverts bitsy-ai/meta-bitsy#345

Revert "Disable browser caching"

---

meta-printnanny/recipes-core/octoprint-apps/files/octoprint.service
meta-printnanny/recipes-httpd/nginx/nginx/octoprint.locations.template

Reverts bitsy-ai/meta-bitsy#344

Revert "bind OctoPrint server to 0.0.0.0:5001"

---

meta-printnanny/recipes-core/python3-octoprint/python3-ed25519_1.5.bb
meta-printnanny/recipes-core/python3-octoprint/python3-nats-py_2.2.0.bb
meta-printnanny/recipes-core/python3-octoprint/python3-nkeys_0.1.0.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/194

Fix: missing nkeys Python package

---

recipes-multimedia/janus-gateway/files/janus.plugin.recordplay.jcfg
recipes-multimedia/janus-gateway/janus-gateway_git.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/198

Configure janus recording plugin

---

meta-printnanny/conf/layer.conf
meta-printnanny/recipes-core/printnanny-gst-plugin/printnanny-gst-plugin.inc
meta-printnanny/recipes-core/printnanny-vision/files/printnanny-vision.service
meta-printnanny/recipes-core/printnanny-vision/printnanny-vision.bb
recipes-multimedia/gst-interpipes/gst-interpipes_v1.1.8.bb
recipes-multimedia/gstd/files/gstd-yocto-disable-gtk-doc.patch
recipes-multimedia/gstd/gstd_0.15.0.bb

https://github.com/bitsy-ai/printnanny-os/issues/205

Port gst-interpipes and gstd-1.0 recipes to new bitbake syntax

---

meta-printnanny/recipes-core/printnanny-gst-plugin/printnanny-gst-plugin.inc
meta-printnanny/recipes-core/printnanny-gst-plugin/printnanny-gst-plugin_git.bb
meta-printnanny/recipes-core/printnanny-rs/printnanny-cli_git.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/205

Update printnanny-rs dependencies with gst-client

---

meta-printnanny/recipes-bsp/sdwire/sdwire_git.bb
meta-printnanny/recipes-core/images/include/core.inc
meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-extras.bb

closes: https://github.com/bitsy-ai/printnanny-os/issues/167

Install printnanny-sdwire cli tool

---

meta-printnanny/recipes-core/printnanny-vision/files/printnanny-vision.service
recipes-multimedia/gstd/gstd_0.15.0.bb

old bitbake syntax preventing this service from starting in enabled state

Fix gstd not starting enabled

---

recipes-bsp/common/raspberrypi-firmware.inc
recipes-kernel/linux-raspberrypi/linux-raspberrypi_%.bbappend
recipes-kernel/linux-raspberrypi/linux-raspberrypi_5.15.bbappend

ref: https://github.com/bitsy-ai/printnanny-os/issues/212

build raspberrypi-linux kernel @ 5.15.87

---

meta-printnanny/recipes-httpd/nginx/nginx/dash.locations.template

ref: https://github.com/bitsy-ai/printnanny-os/issues/211
https://github.com/bitsy-ai/printnanny-os/issues/210

Add nginx location for snapshots

---

meta-printnanny/recipes-core/printnanny-cloud-apps/files/printnanny-recording-sync@.service
meta-printnanny/recipes-core/printnanny-cloud-apps/printnanny-cloud-apps.bb

Ref: https://github.com/bitsy-ai/printnanny-os/issues/198

Install printnanny-recording-sync@.service template

---

recipes-multimedia/gstd/files/gstd.service

closes: https://github.com/bitsy-ai/printnanny-os/issues/221

set GST_DEBUG=3 (FIXME) and strip colors

---

recipes-multimedia/gstd/files/gstd.service

ref: https://github.com/bitsy-ai/printnanny-os/issues/219

Log GST_CAPS and GST_PROBE at INFO level

---

meta-printnanny/recipes-core/printnanny-cloud-apps/files/printnanny-online.target
meta-printnanny/recipes-core/printnanny-core-apps/printnanny-core-apps.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/220

Install printnanny-online.target systemd unit

---

meta-printnanny/recipes-core/printnanny-vision/files/gst-exec-stop.conf
meta-printnanny/recipes-core/printnanny-vision/printnanny-vision.bb
recipes-multimedia/gstd/files/gstd.service

ref: https://github.com/bitsy-ai/printnanny-os/issues/232

Package a gstd stop hook

---

meta-printnanny/recipes-core/python3-octoprint/python3-octoprint_1.8.6.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/229

Install OctoPrint from pypi release (revert building from git source)

---

meta-printnanny/recipes-core/printnanny-core-apps/printnanny-overlayfs.bb
meta-printnanny/recipes-extended/cloud-init/cloud-init-overlayfs.bb
meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud-init-local.service

ref: https://github.com/bitsy-ai/printnanny-os/issues/227

Save cloud-init instance state on persistent partition mount

---

meta-printnanny/recipes-core/images/include/overlayfs-etc.inc
meta-printnanny/recipes-core/images/printnanny-release-image.bb
meta-printnanny/recipes-core/printnanny-core-apps/printnanny-overlayfs.bb
recipes-bsp/bootfiles/rpi-cmdline.bbappend

ref: https://github.com/bitsy-ai/printnanny-os/issues/227

Implement overlayfs for /etc

---

meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-core.bb

ref: https://github.com/bitsy-ai/printnanny-os/issues/267

install: ntp, ntpq, ntpd systemd service

---

meta-printnanny/recipes-core/packagegroups/packagegroup-printnanny-core.bb
meta-printnanny/recipes-extended/cloud-init/cloud-init/cloud.cfg

ref: https://github.com/bitsy-ai/printnanny-os/issues/267

configure: NTP pools + install ntpdate

---

meta-printnanny/recipes-core/printnanny-vision/files/labels.txt
meta-printnanny/recipes-core/printnanny-vision/printnanny-nn.bb

for compatibility with latest nnstreamer build

fix labels file format (remove bg class)

---

recipes-multimedia/janus-gateway/files/janus.jcfg

closes: https://github.com/bitsy-ai/printnanny-os/issues/280

Disable colors in janus-gateway logs

---

recipes-multimedia/janus-gateway/files/janus.plugin.streaming.jcfg

ref: https://github.com/bitsy-ai/printnanny-os/issues/281

Add a default videofmtp and packetization mode

---

meta-printnanny/recipes-core/printnanny-gst-plugin/printnanny-gst-plugin_git.bb
meta-printnanny/recipes-core/printnanny-rs/printnanny-cli_git.bb
meta-printnanny/recipes-core/printnanny-rs/printnanny-snapshot_git.bb
meta-printnanny/recipes-core/python3/python3-versions.inc

ref: https://github.com/bitsy-ai/printnanny-os/issues

Upgrade api libs

---

meta-printnanny/recipes-core/python3-octoprint/python3-octoprint_1.8.7.bb

closes: https://github.com/bitsy-ai/printnanny-os/issues/289

Upgrade octoprint recipe to 1.8.7

---

meta-printnanny/recipes-httpd/nginx/nginx/gstd.locations.template
meta-printnanny/recipes-httpd/nginx/nginx_%.bbappend

ref: https://github.com/bitsy-ai/printnanny-os/issues/288

Install nginx locations template for gstd
